/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mwypych' at '20.11.16 17:22' with Gradle 3.0
 *
 * @author mwypych, @date 20.11.16 17:22
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
